#!/usr/bin/tclsh

if { $argc ==0 } {
        puts "tcltotux.tcl requires one argument specifying the location of a target file"
        exit
} 

set target [lindex $argv 0]

set name ""
set author ""
set width ""
set length ""
set pwidth ""
set plength ""
set start_x ""
set start_y ""
set angle ""
set elev_scale "" 

proc objset {k opt value} {
    switch -glob $opt {
        -course_name  {
            set ::name $value
        } -width {
            set ::width $value
        } -length {
            set ::length $value
        } -play_width {
            set ::pwidth $value
        } -play_length {
            set ::plength $value
        } -angle {
            set ::angle $value
        } -elev_scale {
            set ::elev_scale $value
        } -start_pt {
            set ::start_x [lindex $value 0] 
            set ::start_y [lindex $value 1]
        }
    }

}

#placeholder stuff to satiate tclsh
proc objcall {k opt value} {}
proc tux_course_init {} {} 

source $target 

set data "*\[width] $width \[length] $length \[play_width] $pwidth \[play_length] $plength \n\[startx]$start_x\[starty]$start_y\[angle]$angle\[scale]$elev_scale\n\[theme]calm\n\[env] tuxracer\n\n\[author] $author\n*\[desc] Generated by tcltotux.tcl"
puts $data

