#!/usr/bin/tclsh

if { $argc ==0 } {
        puts "tcltotux.tcl requires one argument specifying the location of a target file"
        exit
} 

set target [lindex $argv 0]

global name ""
global author ""
global width ""
global length ""
global pwidth ""
global plength ""
global start_x ""
global start_y ""
global angle ""
global elev_scale "" 
 
proc tux_course_name {name} {
    set ::name $name
}
proc tux_course_author {author} {
    set ::author $author
} 

#dimension and scale data
proc tux_course_dim {width length pwidth plength} {
    set ::width $width
    set ::length $length
    set ::pwidth $pwidth
    set ::plength $plength
}  
proc tux_start_pt {start_x start_y} {
    set ::start_x $start_x
    set ::start_y $start_y
} 
proc tux_angle  {angle} {
    set ::angle $angle
}
proc tux_elev_scale {elev_scale} {
    set ::elev_scale $elev_scale
} 

#placeholder stuff to satiate tclsh
proc tux_base_height_value {blank} {} 
proc tux_elev {blank} {}
proc tux_terrain {blank} {} 
proc tux_course_init {} {} 

source $target 

set data "*\[width] $width \[length] $length \[play_width] $pwidth \[play_length] $plength \n\[startx]$start_x\[starty]$start_y\[angle]$angle\[scale]$elev_scale\n\[theme]calm\n\[env] tuxracer\n\n\[author] $author\n*\[desc] Generated by tcltotux.tcl"
puts $data

